import { useEffect, useMemo, useState } from 'react';

import {
  clearCache,
  getCacheState,
  updateEnabled,
  updateSettings,
} from '@/interface/shared-ui/settings-client';
import type { AppSettings, CacheState } from '@/shared/types';

interface Props {
  settings: AppSettings;
  onSettingsChange: (settings: AppSettings) => void;
}

const languagePresets = [
  { value: 'en', label: 'English' },
  { value: 'zh-CN', label: '简体中文' },
  { value: 'zh-TW', label: '繁體中文' },
  { value: 'ja', label: '日本語' },
  { value: 'ko', label: '한국어' },
  { value: 'es', label: 'Español' },
];

export function GeneralPage({
  settings,
  onSettingsChange,
}: Props): JSX.Element {
  const [draftTargetLanguage, setDraftTargetLanguage] = useState(
    settings.targetLanguage,
  );
  const [draftSourceLanguage, setDraftSourceLanguage] = useState(
    settings.preferredCaptionLanguage,
  );
  const [allowAutoGenerated, setAllowAutoGenerated] = useState(
    settings.allowAutoGeneratedCaptions,
  );
  const [saving, setSaving] = useState(false);
  const [cacheState, setCacheState] = useState<CacheState | null>(null);
  const activeProviderName = useMemo(
    () =>
      settings.llm.providers.find(
        (provider) => provider.id === settings.llm.activeProviderId,
      )?.name ?? '未配置',
    [settings],
  );

  useEffect(() => {
    setDraftTargetLanguage(settings.targetLanguage);
    setDraftSourceLanguage(settings.preferredCaptionLanguage);
    setAllowAutoGenerated(settings.allowAutoGeneratedCaptions);
  }, [
    settings.allowAutoGeneratedCaptions,
    settings.preferredCaptionLanguage,
    settings.targetLanguage,
  ]);

  useEffect(() => {
    void getCacheState().then(setCacheState);
  }, []);

  const applyTargetLanguage = async (): Promise<void> => {
    setSaving(true);
    try {
      const next = await updateSettings({
        targetLanguage: draftTargetLanguage.trim() || 'zh-CN',
      });
      onSettingsChange(next);
    } finally {
      setSaving(false);
    }
  };

  const applyCaptionPreferences = async (): Promise<void> => {
    setSaving(true);
    try {
      const next = await updateSettings({
        preferredCaptionLanguage: draftSourceLanguage.trim() || 'en',
        allowAutoGeneratedCaptions: allowAutoGenerated,
      });
      onSettingsChange(next);
    } finally {
      setSaving(false);
    }
  };

  const handleClearCache = async (): Promise<void> => {
    setSaving(true);
    try {
      const next = await clearCache();
      setCacheState(next);
    } finally {
      setSaving(false);
    }
  };

  const toggleEnabled = async (): Promise<void> => {
    setSaving(true);
    try {
      const next = await updateEnabled(!settings.enabled);
      onSettingsChange(next);
    } finally {
      setSaving(false);
    }
  };

  return (
    <section className="stack-lg">
      <div className="hero-card">
        <div>
          <p className="eyebrow">General</p>
          <h2>联调前总设置</h2>
          <p className="muted">
            当前状态：
            {settings.enabled ? '已启用' : '已禁用'}
            {' · '}
            目标语言：
            {settings.targetLanguage}
            {' · '}
            Provider：
            {activeProviderName}
          </p>
        </div>
      </div>

      <div className="content-card stack-md">
        <h3>扩展开关</h3>
        <button
          className="primary-button"
          disabled={saving}
          onClick={() => void toggleEnabled()}
          type="button"
        >
          {settings.enabled ? '关闭字幕增强' : '开启字幕增强'}
        </button>
      </div>

      <div className="content-card stack-md">
        <h3>目标语言</h3>
        <div className="form-grid">
          <label>
            <span>快速选择</span>
            <select
              value={draftTargetLanguage}
              onChange={(event) => setDraftTargetLanguage(event.target.value)}
            >
              {languagePresets.map((option) => (
                <option key={option.value} value={option.value}>
                  {option.label} ({option.value})
                </option>
              ))}
            </select>
          </label>
          <label>
            <span>语言代码</span>
            <input
              value={draftTargetLanguage}
              onChange={(event) => setDraftTargetLanguage(event.target.value)}
              placeholder="zh-CN"
            />
          </label>
        </div>

        <button
          className="secondary-button"
          disabled={saving}
          onClick={() => void applyTargetLanguage()}
          type="button"
        >
          保存目标语言
        </button>
      </div>

      <div className="content-card stack-md">
        <h3>源字幕偏好</h3>
        <div className="form-grid">
          <label>
            <span>优先字幕语言</span>
            <select
              value={draftSourceLanguage}
              onChange={(event) => setDraftSourceLanguage(event.target.value)}
            >
              {languagePresets.map((option) => (
                <option key={option.value} value={option.value}>
                  {option.label} ({option.value})
                </option>
              ))}
            </select>
          </label>
          <label>
            <span>字幕语言代码</span>
            <input
              value={draftSourceLanguage}
              onChange={(event) => setDraftSourceLanguage(event.target.value)}
              placeholder="en"
            />
          </label>
        </div>

        <label className="checkbox-row">
          <input
            checked={allowAutoGenerated}
            type="checkbox"
            onChange={(event) => setAllowAutoGenerated(event.target.checked)}
          />
          <span>当人工字幕缺失时，允许回退到 YouTube 自动字幕（ASR）</span>
        </label>

        <p className="muted">
          拿不到可靠字幕轨时会停止处理并显示错误，避免用不同步的实时字幕替代主流程。
        </p>

        <button
          className="secondary-button"
          disabled={saving}
          onClick={() => void applyCaptionPreferences()}
          type="button"
        >
          保存源字幕偏好
        </button>
      </div>

      <div className="content-card stack-md">
        <h3>缓存管理</h3>
        <p className="muted">
          当前缓存条目：
          {cacheState?.count ?? '...'}
          {
            '。切换 provider、模型或字幕策略后，如果结果看起来不对，先清缓存再重试会更稳。'
          }
        </p>

        {cacheState && cacheState.entries.length > 0 ? (
          <div className="stack-sm">
            {cacheState.entries.map((entry) => (
              <div className="cache-row" key={entry.cacheKey}>
                <div className="cache-key">{entry.cacheKey}</div>
                <div className="cache-time">
                  {formatCacheTime(entry.createdAt)}
                </div>
              </div>
            ))}
          </div>
        ) : (
          <p className="muted">当前还没有缓存字幕结果。</p>
        )}

        <button
          className="ghost-button"
          disabled={saving}
          onClick={() => void handleClearCache()}
          type="button"
        >
          清空字幕缓存
        </button>
      </div>
    </section>
  );
}

function formatCacheTime(value: string): string {
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) {
    return value;
  }

  return date.toLocaleString('zh-CN', {
    hour12: false,
  });
}
