import type { CaptionTrack } from '@/shared/types';

export interface CaptionTrackSelectionPreferences {
  preferredLanguage: string;
  allowAutoGenerated: boolean;
}

export function selectCaptionTrack(
  tracks: CaptionTrack[],
  preferences: CaptionTrackSelectionPreferences,
): CaptionTrack | undefined {
  const candidates = preferences.allowAutoGenerated
    ? tracks
    : tracks.filter((track) => track.kind !== 'asr');

  if (candidates.length === 0) {
    return undefined;
  }

  const preferredBase = baseLanguage(preferences.preferredLanguage);
  const sorted = [...candidates].sort((left, right) => {
    return (
      scoreTrack(right, preferences.preferredLanguage, preferredBase) -
      scoreTrack(left, preferences.preferredLanguage, preferredBase)
    );
  });

  return sorted[0];
}

export function selectEnglishCaptionTrack(
  tracks: CaptionTrack[],
  preferences: CaptionTrackSelectionPreferences,
): CaptionTrack | undefined {
  const preferredLanguage = isEnglishLanguage(preferences.preferredLanguage)
    ? preferences.preferredLanguage
    : 'en';

  return selectCaptionTrack(tracks.filter(isEnglishCaptionTrack), {
    ...preferences,
    preferredLanguage,
  });
}

export function isEnglishCaptionTrack(track: CaptionTrack): boolean {
  return isEnglishLanguage(track.languageCode);
}

function scoreTrack(
  track: CaptionTrack,
  preferredLanguage: string,
  preferredBase: string,
): number {
  const trackBase = baseLanguage(track.languageCode);
  const exactMatch = track.languageCode === preferredLanguage ? 1000 : 0;
  const baseMatch = trackBase === preferredBase ? 500 : 0;
  const manualBonus = track.kind === 'asr' ? 0 : 200;
  const humanNameBonus = /auto|automatic|generated/i.test(track.name) ? 0 : 40;
  const shorterLanguageBonus = track.languageCode.length <= 5 ? 10 : 0;

  return (
    exactMatch + baseMatch + manualBonus + humanNameBonus + shorterLanguageBonus
  );
}

function isEnglishLanguage(languageCode: string): boolean {
  return baseLanguage(languageCode) === 'en';
}

function baseLanguage(languageCode: string): string {
  return (
    languageCode.toLowerCase().split(/[-_]/)[0] ?? languageCode.toLowerCase()
  );
}
