import type { SubtitleStyle } from '@/shared/types';

export interface SubtitleStylePreset {
  id: string;
  name: string;
  description: string;
  style: Partial<SubtitleStyle>;
}

export const SUBTITLE_STYLE_PRESETS: SubtitleStylePreset[] = [
  {
    id: 'classic',
    name: '默认风格',
    description: '规划书默认样式，适合大多数视频',
    style: {
      zhColor: '#FFFFFF',
      enColor: '#C8D0DC',
      highlightColor: '#FF4D4D',
      zhFontSizePercent: 100,
      enFontSizePercent: 100,
      maxWidthPercent: 78,
      zhFontWeight: 800,
      enFontWeight: 500,
      lineOrder: 'zh-first',
      lineGapPercent: 22,
      lineHeightPercent: 100,
      strokeWidth: 1,
      shadowStrength: 60,
      backgroundEnabled: false,
    },
  },
  {
    id: 'clear-white',
    name: '清透白',
    description: '白色文字、无背景、轻阴影，干净清晰',
    style: {
      zhColor: '#FFFFFF',
      enColor: '#E2E8F0',
      highlightColor: '#F59E0B',
      zhFontSizePercent: 100,
      enFontSizePercent: 100,
      maxWidthPercent: 76,
      zhFontWeight: 760,
      enFontWeight: 480,
      lineOrder: 'zh-first',
      strokeWidth: 0.6,
      shadowStrength: 44,
      backgroundEnabled: false,
    },
  },
  {
    id: 'outline',
    name: '描边',
    description: '粗描边、无背景，适合浅色画面',
    style: {
      zhColor: '#FFFFFF',
      enColor: '#F1F5F9',
      highlightColor: '#38BDF8',
      zhFontSizePercent: 100,
      enFontSizePercent: 100,
      maxWidthPercent: 78,
      zhFontWeight: 800,
      enFontWeight: 520,
      lineOrder: 'zh-first',
      strokeWidth: 2.2,
      shadowStrength: 40,
      backgroundEnabled: false,
    },
  },
  {
    id: 'just-shadow',
    name: '投影',
    description: '无描边、强投影，柔和自然',
    style: {
      zhColor: '#F8FAFC',
      enColor: '#E2E8F0',
      highlightColor: '#22C55E',
      zhFontSizePercent: 100,
      enFontSizePercent: 100,
      maxWidthPercent: 78,
      zhFontWeight: 760,
      enFontWeight: 480,
      lineOrder: 'zh-first',
      strokeWidth: 0,
      shadowStrength: 92,
      backgroundEnabled: false,
    },
  },
  {
    id: 'paper-note',
    name: '笔记风',
    description: '暖白色、手写感字体，像便签笔记',
    style: {
      zhColor: '#FEF3C7',
      enColor: '#D6CCC0',
      highlightColor: '#F97316',
      zhFontSizePercent: 96,
      enFontSizePercent: 96,
      maxWidthPercent: 70,
      zhFontWeight: 680,
      enFontWeight: 440,
      lineOrder: 'zh-first',
      lineGapPercent: 18,
      strokeWidth: 0.4,
      shadowStrength: 40,
      backgroundEnabled: true,
      backgroundColor: '#1c1917',
      backgroundOpacity: 52,
    },
  },
  {
    id: 'frost-glass',
    name: '磨砂蓝',
    description: '蓝色调半透明背景，科技感',
    style: {
      zhColor: '#BFDBFE',
      enColor: '#93C5FD',
      highlightColor: '#60A5FA',
      zhFontSizePercent: 100,
      enFontSizePercent: 100,
      maxWidthPercent: 76,
      zhFontWeight: 760,
      enFontWeight: 500,
      lineOrder: 'zh-first',
      strokeWidth: 0.8,
      shadowStrength: 56,
      backgroundEnabled: true,
      backgroundColor: '#0c1622',
      backgroundOpacity: 52,
    },
  },
  {
    id: 'cyber-neon',
    name: '霓虹紫',
    description: '紫色高亮、暗背景，赛博朋克风',
    style: {
      zhColor: '#C084FC',
      enColor: '#D8B4FE',
      highlightColor: '#E879F9',
      zhFontSizePercent: 104,
      enFontSizePercent: 100,
      maxWidthPercent: 78,
      zhFontWeight: 820,
      enFontWeight: 520,
      lineOrder: 'zh-first',
      lineGapPercent: 20,
      strokeWidth: 1,
      shadowStrength: 72,
      backgroundEnabled: true,
      backgroundColor: '#0f0f1a',
      backgroundOpacity: 58,
    },
  },
  {
    id: 'cinema',
    name: '影院',
    description: '位置更低、字号略大，适合全屏观看',
    style: {
      zhColor: '#FFFFFF',
      enColor: '#D8DEE9',
      highlightColor: '#F97316',
      bottomOffsetPercent: 9,
      zhFontSizePercent: 112,
      enFontSizePercent: 108,
      maxWidthPercent: 84,
      zhFontWeight: 820,
      enFontWeight: 540,
      lineOrder: 'zh-first',
      lineGapPercent: 20,
      lineHeightPercent: 100,
      strokeWidth: 1.2,
      shadowStrength: 72,
      backgroundEnabled: false,
    },
  },
  {
    id: 'deep-sea',
    name: '深海蓝',
    description: '深蓝背景、亮白字，沉稳专业',
    style: {
      zhColor: '#E0F2FE',
      enColor: '#BAE6FD',
      highlightColor: '#38BDF8',
      zhFontSizePercent: 100,
      enFontSizePercent: 100,
      maxWidthPercent: 76,
      zhFontWeight: 780,
      enFontWeight: 500,
      lineOrder: 'zh-first',
      strokeWidth: 1,
      shadowStrength: 60,
      backgroundEnabled: true,
      backgroundColor: '#0b1622',
      backgroundOpacity: 62,
    },
  },
  {
    id: 'blackboard',
    name: '黑板风',
    description: '深绿背景、粉笔白字，教育场景',
    style: {
      zhColor: '#D9F2C7',
      enColor: '#C3E4A8',
      highlightColor: '#F97316',
      zhFontSizePercent: 100,
      enFontSizePercent: 100,
      maxWidthPercent: 78,
      zhFontWeight: 760,
      enFontWeight: 480,
      lineOrder: 'zh-first',
      lineGapPercent: 20,
      strokeWidth: 0.4,
      shadowStrength: 32,
      backgroundEnabled: true,
      backgroundColor: '#1a2118',
      backgroundOpacity: 64,
    },
  },
  {
    id: 'matrix-green',
    name: '终端绿',
    description: '黑背景、绿色字，极客黑客风',
    style: {
      zhColor: '#22C55E',
      enColor: '#4ADE80',
      highlightColor: '#86EFAC',
      zhFontSizePercent: 100,
      enFontSizePercent: 100,
      maxWidthPercent: 74,
      zhFontWeight: 760,
      enFontWeight: 480,
      lineOrder: 'zh-first',
      lineGapPercent: 18,
      strokeWidth: 0,
      shadowStrength: 36,
      backgroundEnabled: true,
      backgroundColor: '#0a0f0a',
      backgroundOpacity: 68,
    },
  },
  {
    id: 'compact',
    name: '紧凑',
    description: '减少遮挡，适合教程和演示类视频',
    style: {
      zhColor: '#F8FAFC',
      enColor: '#CBD5E1',
      highlightColor: '#38BDF8',
      bottomOffsetPercent: 14,
      zhFontSizePercent: 88,
      enFontSizePercent: 88,
      maxWidthPercent: 68,
      zhFontWeight: 760,
      enFontWeight: 480,
      lineOrder: 'zh-first',
      lineGapPercent: 16,
      lineHeightPercent: 92,
      strokeWidth: 0.8,
      shadowStrength: 52,
      backgroundEnabled: false,
    },
  },
  {
    id: 'macaron-pink',
    name: '桃气粉',
    description: '粉色调、柔和温暖',
    style: {
      zhColor: '#FBCFE8',
      enColor: '#F9A8D4',
      highlightColor: '#F472B6',
      zhFontSizePercent: 100,
      enFontSizePercent: 100,
      maxWidthPercent: 76,
      zhFontWeight: 740,
      enFontWeight: 480,
      lineOrder: 'zh-first',
      lineGapPercent: 22,
      strokeWidth: 0.6,
      shadowStrength: 52,
      backgroundEnabled: true,
      backgroundColor: '#1a1518',
      backgroundOpacity: 52,
    },
  },
  {
    id: 'maple-rust',
    name: '枫叶橙',
    description: '暖棕色调，温馨自然',
    style: {
      zhColor: '#FED7AA',
      enColor: '#FBBF77',
      highlightColor: '#F97316',
      zhFontSizePercent: 100,
      enFontSizePercent: 100,
      maxWidthPercent: 78,
      zhFontWeight: 760,
      enFontWeight: 500,
      lineOrder: 'zh-first',
      lineGapPercent: 22,
      strokeWidth: 0.8,
      shadowStrength: 56,
      backgroundEnabled: true,
      backgroundColor: '#1a1614',
      backgroundOpacity: 54,
    },
  },
  {
    id: 'contrast',
    name: '高对比',
    description: '更醒目，适合画面复杂的视频',
    style: {
      zhColor: '#FFFFFF',
      enColor: '#FFE8A3',
      highlightColor: '#22C55E',
      zhFontSizePercent: 104,
      enFontSizePercent: 104,
      maxWidthPercent: 80,
      zhFontWeight: 860,
      enFontWeight: 620,
      lineOrder: 'zh-first',
      lineGapPercent: 24,
      lineHeightPercent: 104,
      strokeWidth: 1.5,
      shadowStrength: 88,
      backgroundEnabled: true,
      backgroundColor: '#000000',
      backgroundOpacity: 48,
    },
  },
];
