import type { BilingualCue, Cue } from '@/domain/models/Cue';
import type { SubtitleStyle } from '@/domain/models/SubtitleStyle';

export type { SubtitleStyle } from '@/domain/models/SubtitleStyle';

export type ProviderType =
  | 'openai-compatible'
  | 'anthropic'
  | 'gemini'
  | 'custom';

export type ProviderConfig =
  | {
      type: 'openai-compatible';
      id: string;
      name: string;
      baseURL: string;
      apiKey: string;
      model: string;
      headers?: Record<string, string>;
    }
  | {
      type: 'anthropic';
      id: string;
      name: string;
      baseURL?: string;
      apiKey: string;
      model: string;
    }
  | {
      type: 'gemini';
      id: string;
      name: string;
      apiKey: string;
      model: string;
    }
  | {
      type: 'custom';
      id: string;
      name: string;
      baseURL: string;
      method: 'POST';
      headers: Record<string, string>;
      requestTemplate: string;
      responseExtractor: string;
    };

export interface LLMSettings {
  providers: ProviderConfig[];
  activeProviderId: string;
  taskBindings?: {
    translation?: string;
    segmentation?: string;
    vocab?: string;
  };
}

export interface SavedSubtitleStylePreset {
  id: string;
  name: string;
  style: SubtitleStyle;
  createdAt: string;
}

export interface AppSettings {
  enabled: boolean;
  targetLanguage: string;
  preferredCaptionLanguage: string;
  allowAutoGeneratedCaptions: boolean;
  llm: LLMSettings;
  style: SubtitleStyle;
  stylePresets: SavedSubtitleStylePreset[];
}

export type SettingsPatch = Partial<Omit<AppSettings, 'llm' | 'style'>> & {
  llm?: Partial<LLMSettings>;
  style?: Partial<SubtitleStyle>;
};

export interface CaptionTrack {
  baseUrl: string;
  languageCode: string;
  name: string;
  kind?: string;
  vssId?: string;
}

export interface VideoContext {
  videoId: string;
  title: string;
  channel?: string;
  currentChapter?: string;
  captionTracks?: CaptionTrack[];
  captionTrack?: CaptionTrack;
  sourceLanguage?: string;
}

export interface PipelinePayload {
  video: VideoContext;
  sourceSubtitles?: {
    cues: Cue[];
    sourceLanguage: string;
  };
}

export interface SourceSubtitlesPayload {
  videoId?: string;
  captionTrack?: CaptionTrack;
  captionTracks?: CaptionTrack[];
}

export interface SourceSubtitlesResponse {
  cues: Cue[];
  sourceLanguage: string;
}

export interface LiveTranslatePayload {
  video: VideoContext;
  cueText: string;
  /**
   * 来自 Google MT 的草稿译文。如果提供了，LLM 任务从"翻译"
   * 退化成"润色 + 去机翻味"——更快也更省 token。
   */
  draftTranslation?: string;
}

export interface LiveTranslateResponse {
  ok: true;
  translation: string;
}

export interface InstantTranslatePayload {
  text: string;
  sourceLanguage?: string;
}

export type InstantTranslateResponse =
  | { ok: true; translation: string }
  | { ok: false; error: string };

export interface AiPolishBatchItem {
  sentenceId: string;
  sourceText: string;
  draftTranslation: string;
  start: number;
  end: number;
}

export interface AiPolishBatchPayload {
  video: VideoContext;
  sourceLanguage?: string;
  items: AiPolishBatchItem[];
}

export type AiPolishBatchResponse =
  | {
      ok: true;
      translations: Array<{
        sentenceId: string;
        translation: string;
      }>;
    }
  | { ok: false; error: string };

export interface SubtitleCachePutPayload {
  video: VideoContext;
  cues: BilingualCue[];
}

export type SubtitleCachePutResponse =
  | { ok: true }
  | { ok: false; error: string };

export interface EnsureCaptionsPayload {
  preferredLanguage: string;
  allowAutoGenerated: boolean;
  forceReload?: boolean;
}

export type EnsureCaptionsResponse =
  | {
      ok: true;
      opened: boolean;
      selectedTrackName?: string;
      domButtonPressed?: boolean;
      usedButtonClick?: boolean;
    }
  | { ok: false; error: string };

export type InstallCaptureHookResponse =
  | { ok: true; alreadyInstalled: boolean }
  | { ok: false; error: string };

export interface ParseCapturedCaptionPayload {
  text: string;
  url: string;
  languageCode?: string;
}

export type ParseCapturedCaptionResponse =
  | { ok: true; cues: Cue[]; sourceLanguage: string }
  | { ok: false; error: string };

export interface AiSummarizePayload {
  video: VideoContext;
  subtitleText: string;
  deepThink?: boolean;
}

export type AiSummarizeResponse =
  | { ok: true; summary: string }
  | { ok: false; error: string };

export interface AiAskPayload {
  video: VideoContext;
  question: string;
  context?: string;
  selectedText?: string;
}

export type AiAskResponse =
  | { ok: true; answer: string }
  | { ok: false; error: string };

export interface AiTranscribePayload {
  video: VideoContext;
  cues: Array<{ start: number; end: number; text: string }>;
}

export type AiTranscribeResponse =
  | { ok: true; segments: Array<{ start: number; speaker?: string; text: string }> }
  | { ok: false; error: string };

export interface DebugLogEntry {
  id: string;
  timestamp: string;
  level: 'info' | 'warn' | 'error';
  source: 'content' | 'background' | 'shared';
  event: string;
  details?: string;
}

export interface PipelineSuccessResponse {
  ok: true;
  data: {
    cues: BilingualCue[];
    style: SubtitleStyle;
    sourceLanguage: string;
    targetLanguage: string;
  };
}

export interface PipelineErrorResponse {
  ok: false;
  error: string;
}

export type PipelineResponse = PipelineSuccessResponse | PipelineErrorResponse;

export interface ProviderTestSuccessResponse {
  ok: true;
  providerId: string;
  providerType: ProviderType;
  responsePreview: string;
}

export interface ProviderTestErrorResponse {
  ok: false;
  providerId: string;
  providerType: ProviderType;
  error: string;
}

export type ProviderTestResponse =
  | ProviderTestSuccessResponse
  | ProviderTestErrorResponse;

export interface CacheState {
  count: number;
  entries: Array<{
    cacheKey: string;
    createdAt: string;
  }>;
}

export interface MessageMap {
  'fanyi/pipeline-run': PipelinePayload;
  'fanyi/settings-get': undefined;
  'fanyi/settings-update': SettingsPatch;
  'fanyi/provider-upsert': ProviderConfig;
  'fanyi/provider-delete': { providerId: string };
  'fanyi/provider-activate': { providerId: string };
  'fanyi/provider-test': ProviderConfig;
  'fanyi/source-subtitles-fetch': SourceSubtitlesPayload;
  'fanyi/live-translate': LiveTranslatePayload;
  'fanyi/instant-translate': InstantTranslatePayload;
  'fanyi/ai-polish-batch': AiPolishBatchPayload;
  'fanyi/subtitle-cache-put': SubtitleCachePutPayload;
  'fanyi/ensure-captions': EnsureCaptionsPayload;
  'fanyi/install-capture-hook': undefined;
  'fanyi/parse-captured-caption': ParseCapturedCaptionPayload;
  'fanyi/debug-logs-get': undefined;
  'fanyi/debug-logs-clear': undefined;
  'fanyi/cache-get': undefined;
  'fanyi/cache-clear': undefined;
  'fanyi/style-update': Partial<SubtitleStyle>;
  'fanyi/enabled-update': { enabled: boolean };
  'fanyi/ai-summarize': AiSummarizePayload;
  'fanyi/ai-ask': AiAskPayload;
  'fanyi/ai-transcribe': AiTranscribePayload;
}

export type MessageType = keyof MessageMap;

export interface MessageEnvelope<T extends MessageType = MessageType> {
  type: T;
  payload: MessageMap[T];
}

export type AnyMessageEnvelope = {
  [K in MessageType]: MessageEnvelope<K>;
}[MessageType];

export const STORAGE_KEYS = {
  settings: 'fanyi:settings',
} as const;

export const DEFAULT_STYLE: SubtitleStyle = {
  zhFontFamily:
    '"PingFang SC", "Microsoft YaHei UI", "Noto Sans SC", system-ui, sans-serif',
  enFontFamily: '"Inter", "SF Pro Text", "Segoe UI", system-ui, sans-serif',
  zhColor: '#FFFFFF',
  enColor: '#C8D0DC',
  highlightColor: '#FF4D4D',
  bottomOffsetPercent: 12,
  scalePercent: 100,
  zhFontSizePercent: 100,
  enFontSizePercent: 100,
  showChinese: true,
  showEnglish: true,
  maxWidthPercent: 78,
  zhFontWeight: 800,
  enFontWeight: 500,
  lineOrder: 'zh-first',
  lineGapPercent: 22,
  lineHeightPercent: 100,
  strokeWidth: 1,
  shadowStrength: 60,
  backgroundEnabled: false,
  backgroundColor: '#000000',
  backgroundOpacity: 42,
};

export const DEFAULT_SETTINGS: AppSettings = {
  enabled: true,
  targetLanguage: 'zh-CN',
  preferredCaptionLanguage: 'en',
  allowAutoGeneratedCaptions: true,
  llm: {
    providers: [],
    activeProviderId: '',
  },
  style: DEFAULT_STYLE,
  stylePresets: [],
};
