import { selectEnglishCaptionTrack } from '@/shared/caption-track-selection';
import { appendDebugLog, summarizeUnknown } from '@/shared/debug-log';
import { logger } from '@/shared/logger';
import { STORAGE_KEYS, type AppSettings } from '@/shared/types';

import {
  discardCapturesFromOtherVideos,
  ensureCaptureHook,
} from './caption-capture-buffer';
import { getSettings, updateEnabled, updateStyleSettings } from './messaging';
import { PlayerControlButton } from './player-control-button';
import {
  acquireSourceSubtitles,
  getSourceSubtitleUnavailableMessage,
} from './source-subtitles';
import { SubtitleDisplaySession } from './subtitle-display-session';
import {
  getInitialTranslationLoadingMessage,
  startAiPolish,
  translateSourceSubtitles,
  type SubtitlePolishHandle,
} from './translated-subtitles';
import {
  bindYouTubePlayer,
  type BoundVideoContext,
} from './youtube-dom-binding';

let rafId = 0;
let displaySession: SubtitleDisplaySession | null = null;
let polishHandle: SubtitlePolishHandle | null = null;
let currentBinding: BoundVideoContext | null = null;
let playerControl: PlayerControlButton | null = null;
let settingsModal: import('./settings-modal').SettingsModal | null = null;
let activeRunId = 0;
let settingsChangeListenerInstalled = false;
let settingsReprocessTimer: number | null = null;

function start(): void {
  void appendDebugLog({
    level: 'info',
    source: 'content',
    event: 'content.script-start',
    details: summarizeUnknown({
      href: location.href,
      readyState: document.readyState,
    }),
  });

  // Install this before YouTube has a chance to fetch captions.
  void ensureCaptureHook();
  installSettingsChangeListener();

  bindYouTubePlayer((binding) => {
    currentBinding = binding;
    void appendDebugLog({
      level: 'info',
      source: 'content',
      event: 'content.video-binding-ready',
      details: summarizeUnknown({
        videoId: binding.context.videoId,
        title: binding.context.title,
        trackCount: binding.context.captionTracks?.length ?? 0,
      }),
    });
    void initializeContentExperience(binding);
  });
}

async function initializeContentExperience(
  binding: BoundVideoContext,
): Promise<void> {
  const runId = ++activeRunId;
  const isCurrentRun = (): boolean => runId === activeRunId;
  const { context, player, video } = binding;

  try {
    resetCurrentSession();

    playerControl = new PlayerControlButton({
      player,
      enabled: false,
      onToggle: async (enabled) => {
        await setFeatureEnabled(enabled);
      },
    });

    const settings = await getSettings();
    if (!isCurrentRun()) return;

    playerControl.setEnabled(settings.enabled);

    void appendDebugLog({
      level: 'info',
      source: 'content',
      event: 'content.settings-loaded',
      details: summarizeUnknown({
        enabled: settings.enabled,
        targetLanguage: settings.targetLanguage,
        preferredCaptionLanguage: settings.preferredCaptionLanguage,
        allowAutoGeneratedCaptions: settings.allowAutoGeneratedCaptions,
      }),
    });

    if (!settings.enabled) {
      return;
    }

    const selectedTrack = selectEnglishCaptionTrack(
      context.captionTracks ?? [],
      {
        preferredLanguage: settings.preferredCaptionLanguage,
        allowAutoGenerated: settings.allowAutoGeneratedCaptions,
      },
    );
    void appendDebugLog({
      level: 'info',
      source: 'content',
      event: 'content.track-selected',
      details: summarizeUnknown({
        trackCount: context.captionTracks?.length ?? 0,
        selectedTrack,
      }),
    });

    if (!selectedTrack) {
      handleMissingEnglishTrack(binding, context.captionTracks?.length ?? 0);
      return;
    }

    const session = createDisplaySession(binding);
    session.setLoading('Fanyi 正在抓取 YouTube 字幕...');
    beginRenderLoop(video);

    discardCapturesFromOtherVideos(context.videoId);

    const sourceSubtitles = await acquireSourceSubtitles({
      context,
      selectedTrack,
      settings,
    });
    if (!isCurrentRun()) return;

    if (!sourceSubtitles) {
      session.setError(getSourceSubtitleUnavailableMessage(settings));
      return;
    }

    void appendDebugLog({
      level: 'info',
      source: 'content',
      event: 'content.source-subtitles-loaded',
      details: summarizeUnknown({
        sourceLanguage: sourceSubtitles.sourceLanguage,
        cueCount: sourceSubtitles.cues.length,
        firstCue: sourceSubtitles.cues[0],
      }),
    });

    session.setLoading(
      getInitialTranslationLoadingMessage(sourceSubtitles.cues.length),
    );
    const translated = await translateSourceSubtitles({
      context,
      selectedTrack,
      sourceSubtitles,
    });
    if (!isCurrentRun()) return;

    session.setLoading('Fanyi 正在渲染字幕...');
    session.setData(translated.cues, translated.style);
    polishHandle = startAiPolish({
      translated,
      video,
      settings,
      isCurrentRun,
      onUpdate: (cues) => {
        if (!isCurrentRun()) return;
        displaySession?.setData(cues, translated.style);
      },
    });
  } catch (error) {
    if (!isCurrentRun()) return;

    logger.error('Failed to initialize content experience.', error);
    void appendDebugLog({
      level: 'error',
      source: 'content',
      event: 'content.initialize-error',
      details: summarizeUnknown(error),
    });

    const message =
      error instanceof Error ? error.message : '初始化失败，请刷新页面重试。';
    if (displaySession) {
      displaySession.setError(message);
    } else {
      renderBootstrapError(message);
    }
  }
}

function resetCurrentSession(): void {
  cancelAnimationFrame(rafId);
  polishHandle?.stop();
  polishHandle = null;
  displaySession?.destroy();
  displaySession = null;
  playerControl?.destroy();
  playerControl = null;
}

function beginRenderLoop(video: HTMLVideoElement): void {
  const render = (): void => {
    displaySession?.update(video.currentTime);
    rafId = requestAnimationFrame(render);
  };

  render();
}

function installSettingsChangeListener(): void {
  if (settingsChangeListenerInstalled) return;
  if (typeof chrome === 'undefined' || !chrome.storage?.onChanged) return;

  settingsChangeListenerInstalled = true;
  chrome.storage.onChanged.addListener((changes, areaName) => {
    if (areaName !== 'local') return;

    const change = changes[STORAGE_KEYS.settings];
    if (!change || !currentBinding) return;

    const oldSettings = change.oldValue as AppSettings | undefined;
    const newSettings = change.newValue as AppSettings | undefined;
    if (!newSettings) return;

    if (shouldReprocessForSettingsChange(oldSettings, newSettings)) {
      scheduleCurrentVideoReprocess();
      return;
    }

    if (hasStyleChanged(oldSettings, newSettings)) {
      displaySession?.updateStyle(newSettings.style);
    }
  });
}

function shouldReprocessForSettingsChange(
  oldSettings: AppSettings | undefined,
  newSettings: AppSettings,
): boolean {
  return (
    oldSettings?.enabled !== newSettings.enabled ||
    oldSettings?.targetLanguage !== newSettings.targetLanguage ||
    oldSettings?.preferredCaptionLanguage !==
      newSettings.preferredCaptionLanguage ||
    oldSettings?.allowAutoGeneratedCaptions !==
      newSettings.allowAutoGeneratedCaptions ||
    JSON.stringify(oldSettings?.llm) !== JSON.stringify(newSettings.llm)
  );
}

function hasStyleChanged(
  oldSettings: AppSettings | undefined,
  newSettings: AppSettings,
): boolean {
  return (
    JSON.stringify(oldSettings?.style) !== JSON.stringify(newSettings.style)
  );
}

function scheduleCurrentVideoReprocess(): void {
  if (!currentBinding) return;

  activeRunId += 1;
  if (settingsReprocessTimer !== null) {
    window.clearTimeout(settingsReprocessTimer);
  }

  settingsReprocessTimer = window.setTimeout(() => {
    settingsReprocessTimer = null;
    const binding = currentBinding;
    if (!binding) return;

    void appendDebugLog({
      level: 'info',
      source: 'content',
      event: 'content.settings-change-reprocess',
      details: '字幕相关设置已变化，重新处理当前视频。',
    });
    void initializeContentExperience(binding);
  }, 150);
}

function createDisplaySession(
  binding: BoundVideoContext,
): SubtitleDisplaySession {
  const session = new SubtitleDisplaySession({
    player: binding.player,
    video: binding.video,
    onPositionChange: (next) => {
      void updateStyleSettings({ customPosition: next }).catch((error) => {
        void appendDebugLog({
          level: 'warn',
          source: 'content',
          event: 'content.position-persist-failed',
          details: summarizeUnknown(error),
        });
      });
    },
    onStyleChange: (patch) => {
      void updateStyleSettings(patch).catch((error) => {
        void appendDebugLog({
          level: 'warn',
          source: 'content',
          event: 'content.toolbar-style-change-failed',
          details: summarizeUnknown(error),
        });
      });
    },
    onOpenSettings: () => {
      void getSettings().then((s) => {
        if (!settingsModal) {
          import('./settings-modal').then(({ SettingsModal }) => {
            settingsModal = new SettingsModal();
            settingsModal!.show(s);
          });
        } else {
          settingsModal.show(s);
        }
      });
    },
  });
  displaySession = session;
  return session;
}

function handleMissingEnglishTrack(
  binding: BoundVideoContext,
  trackCount: number,
): void {
  void appendDebugLog({
    level: 'info',
    source: 'content',
    event: 'content.english-track-skip',
    details: summarizeUnknown({
      videoId: binding.context.videoId,
      trackCount,
      languages: binding.context.captionTracks?.map(
        (track) => track.languageCode,
      ),
    }),
  });

  if (trackCount > 0) {
    return;
  }

  const session = createDisplaySession(binding);
  session.setError('Fanyi 未检测到英文字幕，已跳过本视频。');
}

async function setFeatureEnabled(enabled: boolean): Promise<void> {
  try {
    const nextSettings = await updateEnabled(enabled);
    playerControl?.setEnabled(nextSettings.enabled);
  } catch (error) {
    void appendDebugLog({
      level: 'warn',
      source: 'content',
      event: 'content.player-control-toggle-failed',
      details: summarizeUnknown(error),
    });
    throw error;
  }
}

function renderBootstrapError(message: string): void {
  const existing = document.getElementById('fanyi-bootstrap-error');
  if (existing) {
    existing.textContent = `Fanyi: ${message}`;
    return;
  }

  const node = document.createElement('div');
  node.id = 'fanyi-bootstrap-error';
  node.textContent = `Fanyi: ${message}`;
  node.style.cssText = `
    position: fixed;
    top: 88px;
    right: 16px;
    z-index: 2147483647;
    max-width: 360px;
    padding: 10px 12px;
    border-radius: 14px;
    background: rgba(127, 29, 29, 0.96);
    color: white;
    font: 600 13px/1.45 system-ui, sans-serif;
    box-shadow: 0 12px 28px rgba(0,0,0,0.28);
  `;
  document.body.append(node);
}

start();
