import type { Cue } from '@/domain/models/Cue';
import { appendDebugLog, summarizeUnknown } from '@/shared/debug-log';
import type { AppSettings, CaptionTrack } from '@/shared/types';

import { withTimeout } from './async-utils';
import {
  ensureCaptureHook,
  waitForNextCapture,
} from './caption-capture-buffer';
import {
  requestEnsureCaptions,
  requestParseCapturedCaption,
  requestSourceSubtitles,
} from './messaging';

export interface SourceSubtitleResult {
  cues: Cue[];
  sourceLanguage: string;
}

export async function acquireSourceSubtitles(input: {
  context: { videoId: string; captionTracks?: CaptionTrack[] };
  selectedTrack?: CaptionTrack;
  settings: AppSettings;
}): Promise<SourceSubtitleResult | null> {
  await ensureCaptureHook();
  await ensureNativeCaptions(input, false);

  const source = await firstSuccessfulSource([
    acquireSourceFromCapture(input, 9000),
    acquireSourceFromBackgroundFetch(input),
  ]);
  if (source) {
    return source;
  }

  void appendDebugLog({
    level: 'warn',
    source: 'content',
    event: 'content.source-force-caption-reload',
    details:
      '常规字幕抓取失败，尝试通过播放器 CC 按钮强制重新加载原生字幕请求。',
  });

  await ensureNativeCaptions(input, true);
  return await acquireSourceFromCapture(input, 12000);
}

export function getSourceSubtitleUnavailableMessage(settings: AppSettings): string {
  if (settings.allowAutoGeneratedCaptions) {
    return '未获取到可用字幕轨。已尝试人工字幕和 YouTube 自动字幕，请确认视频播放器能打开字幕，或刷新页面重试。';
  }

  return '未获取到人工字幕轨。可在弹窗中勾选“没有人工字幕时允许自动字幕”，Fanyi 会自动重试当前视频。';
}

async function ensureNativeCaptions(
  input: {
    settings: AppSettings;
  },
  forceReload: boolean,
): Promise<void> {
  try {
    const ensureResult = await withTimeout(
      requestEnsureCaptions({
        preferredLanguage: input.settings.preferredCaptionLanguage,
        allowAutoGenerated: input.settings.allowAutoGeneratedCaptions,
        forceReload,
      }),
      5000,
      forceReload
        ? '强制重新加载 YouTube 原生字幕超时。'
        : '开启 YouTube 原生字幕超时。',
    );
    void appendDebugLog({
      level: ensureResult.ok && ensureResult.opened ? 'info' : 'warn',
      source: 'content',
      event: forceReload
        ? 'content.ensure-captions-force-result'
        : 'content.ensure-captions-result',
      details: summarizeUnknown(ensureResult),
    });
  } catch (error) {
    void appendDebugLog({
      level: 'warn',
      source: 'content',
      event: forceReload
        ? 'content.ensure-captions-force-failed'
        : 'content.ensure-captions-failed',
      details: summarizeUnknown(error),
    });
  }
}

async function acquireSourceFromCapture(
  input: {
    context: { videoId: string };
    selectedTrack?: CaptionTrack;
  },
  timeoutMs: number,
): Promise<SourceSubtitleResult | null> {
  const captured = await waitForNextCapture(timeoutMs, input.context.videoId);
  if (!captured) {
    void appendDebugLog({
      level: 'warn',
      source: 'content',
      event: 'content.source-capture-timeout',
      details: `截获 YouTube fetch 在 ${Math.round(
        timeoutMs / 1000,
      )}s 内未触发。`,
    });
    return null;
  }

  const parsed = await requestParseCapturedCaption({
    text: captured.text,
    url: captured.url,
    languageCode: input.selectedTrack?.languageCode,
  });

  if (parsed.ok && parsed.cues.length > 0) {
    void appendDebugLog({
      level: 'info',
      source: 'content',
      event: 'content.source-from-capture',
      details: summarizeUnknown({
        url: captured.url,
        cueCount: parsed.cues.length,
        sourceLanguage: parsed.sourceLanguage,
      }),
    });
    return { cues: parsed.cues, sourceLanguage: parsed.sourceLanguage };
  }

  void appendDebugLog({
    level: 'warn',
    source: 'content',
    event: 'content.source-capture-parse-failed',
    details: summarizeUnknown(parsed),
  });
  return null;
}

async function acquireSourceFromBackgroundFetch(input: {
  context: { videoId: string; captionTracks?: CaptionTrack[] };
  selectedTrack?: CaptionTrack;
}): Promise<SourceSubtitleResult | null> {
  try {
    const rawSourceSubtitles = await withTimeout(
      requestSourceSubtitles({
        videoId: input.context.videoId,
        captionTrack: input.selectedTrack,
        captionTracks: input.context.captionTracks,
      }),
      15000,
      '抓取字幕超时，请确认这个视频本身能在 YouTube 打开字幕。',
    );

    const sourceError = extractSourceSubtitlesError(rawSourceSubtitles);
    if (sourceError) {
      void appendDebugLog({
        level: 'error',
        source: 'content',
        event: 'content.source-subtitles-error',
        details: summarizeUnknown(rawSourceSubtitles),
      });
      return null;
    }

    const sourceSubtitles = normalizeSourceSubtitles(rawSourceSubtitles);
    if (!sourceSubtitles) {
      void appendDebugLog({
        level: 'error',
        source: 'content',
        event: 'content.invalid-source-subtitles-shape',
        details: summarizeUnknown(rawSourceSubtitles),
      });
      return null;
    }

    void appendDebugLog({
      level: 'info',
      source: 'content',
      event: 'content.source-from-background-fetch',
      details: summarizeUnknown({
        sourceLanguage: sourceSubtitles.sourceLanguage,
        cueCount: sourceSubtitles.cues.length,
      }),
    });
    return sourceSubtitles;
  } catch (error) {
    void appendDebugLog({
      level: 'error',
      source: 'content',
      event: 'content.source-fallback-fetch-error',
      details: summarizeUnknown(error),
    });
    return null;
  }
}

async function firstSuccessfulSource(
  promises: Array<Promise<SourceSubtitleResult | null>>,
): Promise<SourceSubtitleResult | null> {
  return await new Promise((resolve) => {
    let pending = promises.length;
    let settled = false;

    promises.forEach((promise) => {
      void promise
        .then((value) => {
          pending -= 1;
          if (!settled && value) {
            settled = true;
            resolve(value);
            return;
          }
          if (!settled && pending === 0) {
            resolve(null);
          }
        })
        .catch(() => {
          pending -= 1;
          if (!settled && pending === 0) {
            resolve(null);
          }
        });
    });
  });
}

function extractSourceSubtitlesError(value: unknown): string | null {
  if (!value || typeof value !== 'object') {
    return null;
  }

  const candidate = value as { ok?: unknown; error?: unknown };
  if (candidate.ok === false && typeof candidate.error === 'string') {
    return candidate.error;
  }

  return null;
}

function normalizeSourceSubtitles(value: unknown): SourceSubtitleResult | null {
  if (!value || typeof value !== 'object') {
    return null;
  }

  const candidate = value as {
    cues?: unknown;
    sourceLanguage?: unknown;
  };

  if (!Array.isArray(candidate.cues)) {
    return null;
  }

  const cues = candidate.cues.filter(isCue);
  if (cues.length === 0) {
    return null;
  }

  const sourceLanguage =
    typeof candidate.sourceLanguage === 'string' &&
    candidate.sourceLanguage.length > 0
      ? candidate.sourceLanguage
      : 'en';

  return {
    cues,
    sourceLanguage,
  };
}

function isCue(value: unknown): value is Cue {
  if (!value || typeof value !== 'object') {
    return false;
  }

  const candidate = value as Partial<Cue>;
  return (
    typeof candidate.id === 'string' &&
    typeof candidate.start === 'number' &&
    Number.isFinite(candidate.start) &&
    typeof candidate.end === 'number' &&
    Number.isFinite(candidate.end) &&
    candidate.end > candidate.start &&
    typeof candidate.text === 'string' &&
    candidate.text.trim().length > 0
  );
}
