import type { AppSettings } from '@/shared/types';
import { updateEnabled, updateSettings } from '@/interface/shared-ui/settings-client';

interface Props {
  settings: AppSettings;
  onSettingsChange: (s: AppSettings) => void;
}

const LANGUAGES = [
  { value: 'en', label: 'English' },
  { value: 'zh-CN', label: '简体中文' },
  { value: 'zh-TW', label: '繁體中文' },
  { value: 'ja', label: '日本語' },
  { value: 'ko', label: '한국어' },
  { value: 'es', label: 'Español' },
];

export function SubtitleLanguagePage({ settings, onSettingsChange }: Props): JSX.Element {
  const handleToggle = async () => {
    const next = await updateEnabled(!settings.enabled);
    onSettingsChange(next);
  };

  const handleTargetLang = async (v: string) => {
    const next = await updateSettings({ targetLanguage: v });
    onSettingsChange(next);
  };

  const handleSourcePrefs = async (lang: string, auto: boolean) => {
    const next = await updateSettings({ preferredCaptionLanguage: lang, allowAutoGeneratedCaptions: auto });
    onSettingsChange(next);
  };

  return (
    <div>
      <h1 className="sp-page-title">字幕语言</h1>

      <div className="sp-control-group" style={{ marginBottom: 16 }}>
        <div className="sp-control-group-title">扩展开关</div>
        <div className="sp-label">
          <span>启用字幕增强</span>
          <input type="checkbox" checked={settings.enabled} onChange={() => { void handleToggle(); }} />
        </div>
      </div>

      <div className="sp-control-group" style={{ marginBottom: 16 }}>
        <div className="sp-control-group-title">目标翻译语言</div>
        <div className="sp-label">
          <span>快速选择</span>
          <select value={settings.targetLanguage} onChange={(e) => { void handleTargetLang(e.target.value); }}>
            {LANGUAGES.map((l) => (
              <option key={l.value} value={l.value}>{l.label} ({l.value})</option>
            ))}
          </select>
        </div>
        <div className="sp-label">
          <span>自定义语言代码</span>
          <input
            type="text"
            value={settings.targetLanguage}
            onChange={(e) => { void handleTargetLang(e.target.value); }}
            placeholder="zh-CN"
            style={{ background: 'rgba(255,255,255,0.08)', border: '1px solid rgba(255,255,255,0.12)', borderRadius: 6, padding: '4px 8px', color: '#e2e8f0', width: 120 }}
          />
        </div>
      </div>

      <div className="sp-control-group">
        <div className="sp-control-group-title">源字幕偏好</div>
        <div className="sp-label">
          <span>优先字幕语言</span>
          <select value={settings.preferredCaptionLanguage} onChange={(e) => { void handleSourcePrefs(e.target.value, settings.allowAutoGeneratedCaptions); }}>
            {LANGUAGES.map((l) => (
              <option key={l.value} value={l.value}>{l.label} ({l.value})</option>
            ))}
          </select>
        </div>
        <div className="sp-label" style={{ flexDirection: 'column', alignItems: 'flex-start', gap: 4 }}>
          <label style={{ display: 'flex', gap: 8, alignItems: 'center', cursor: 'pointer' }}>
            <input
              type="checkbox"
              checked={settings.allowAutoGeneratedCaptions}
              onChange={(e) => { void handleSourcePrefs(settings.preferredCaptionLanguage, e.target.checked); }}
            />
            <span>允许回退到 YouTube 自动字幕（ASR）</span>
          </label>
          <span style={{ fontSize: 11, color: '#64748b' }}>拿不到可靠字幕轨时会停止处理并显示错误，避免用不同步的实时字幕替代主流程。</span>
        </div>
      </div>
    </div>
  );
}
