import { describe, expect, it } from 'vitest';

import {
  selectCaptionTrack,
  selectEnglishCaptionTrack,
} from '@/shared/caption-track-selection';

describe('selectCaptionTrack', () => {
  it('prefers manual subtitles in the requested language', () => {
    const selected = selectCaptionTrack(
      [
        {
          baseUrl: 'https://example.com/asr',
          languageCode: 'en',
          name: 'English (auto-generated)',
          kind: 'asr',
        },
        {
          baseUrl: 'https://example.com/manual',
          languageCode: 'en',
          name: 'English',
        },
      ],
      {
        preferredLanguage: 'en',
        allowAutoGenerated: true,
      },
    );

    expect(selected?.baseUrl).toBe('https://example.com/manual');
  });

  it('falls back to auto-generated subtitles when allowed', () => {
    const selected = selectCaptionTrack(
      [
        {
          baseUrl: 'https://example.com/asr',
          languageCode: 'en-US',
          name: 'English (auto-generated)',
          kind: 'asr',
        },
      ],
      {
        preferredLanguage: 'en',
        allowAutoGenerated: true,
      },
    );

    expect(selected?.kind).toBe('asr');
  });

  it('returns undefined when only auto-generated subtitles exist but they are disallowed', () => {
    const selected = selectCaptionTrack(
      [
        {
          baseUrl: 'https://example.com/asr',
          languageCode: 'en-US',
          name: 'English (auto-generated)',
          kind: 'asr',
        },
      ],
      {
        preferredLanguage: 'en',
        allowAutoGenerated: false,
      },
    );

    expect(selected).toBeUndefined();
  });

  it('does not select non-English tracks for the English-only content flow', () => {
    const selected = selectEnglishCaptionTrack(
      [
        {
          baseUrl: 'https://example.com/zh',
          languageCode: 'zh-CN',
          name: 'Chinese',
        },
      ],
      {
        preferredLanguage: 'en',
        allowAutoGenerated: true,
      },
    );

    expect(selected).toBeUndefined();
  });

  it('keeps English selection even when another preferred language is configured', () => {
    const selected = selectEnglishCaptionTrack(
      [
        {
          baseUrl: 'https://example.com/zh',
          languageCode: 'zh-CN',
          name: 'Chinese',
        },
        {
          baseUrl: 'https://example.com/en',
          languageCode: 'en',
          name: 'English',
        },
      ],
      {
        preferredLanguage: 'zh-CN',
        allowAutoGenerated: true,
      },
    );

    expect(selected?.languageCode).toBe('en');
  });
});
